export const articlesCopy = {
  en: {
    title: "Articles",
    description: "Products, suppliers, prices and sourcing locations.",
    newArticle: "New article",
    createArticle: "Create article",
    creating: "Creating...",
    createDescription: "Add the product, its supplier, prices and sourcing details.",
    search: "Search articles...",
    article: "Product",
    sku: "SKU",
    category: "Category",
    supplier: "Supplier",
    purchasePrice: "Purchase price",
    salePrice: "Sale price",
    transportCost: "Transport cost",
    paymentCommission: "Payment commission",
    chinaTransportCost: "Purchase transport",
    agencyTransportCost: "Agency transport",
    gainMultiplier: "Gain multiplier (×1.5–×10)",
    totalCost: "Total cost",
    suggestedSalePrice: "Suggested sale price",
    markup: "Markup",
    location: "Location",
    added: "Created",
    rating: "Rating",
    reviews: "reviews",
    stock: "Stock",
    units: "units",
    buy: "Buy",
    buying: "Buying...",
    outOfStock: "Out of stock",
    information: "Information",
    images: "PNG images",
    imagesHint: "Optional — up to 8 PNG images.",
    imagePicker: {
      choose: "Choose PNG files",
      drop: "Drop your PNG images here",
      paste: "or paste an image with Ctrl/Cmd + V",
      format: "PNG only · 1 MB maximum per image · 8 images maximum",
      invalidType: "Only PNG images are accepted.",
      tooLarge: "Each image must be 1 MB or smaller.",
      tooMany: "You can add up to 8 images.",
      remove: "Remove",
    },
    namePlaceholder: "e.g. Premium steel watch",
    skuPlaceholder: "Optional — generated automatically",
    categoryPlaceholder: "e.g. Accessories",
    selectCategory: "Select a category",
    createCategoryFromList: "Create a category",
    createCategory: "Create",
    creatingCategory: "Creating...",
    newCategoryName: "New category name",
    categoryErrors: {
      invalid: "Enter a valid category name.",
      duplicate: "This category already exists.",
      unauthorized: "Your session has expired. Sign in again.",
      unknown: "The category could not be created. Please try again.",
    },
    supplierPlaceholder: "e.g. Atlas Trading",
    city: "City of origin",
    selectCity: "Select a city",
    newCityPlaceholder: "Add a city",
    addCity: "Add",
    cityErrors: { invalid: "Enter a valid city.", duplicate: "This city already exists.", unauthorized: "Your session has expired.", unknown: "The city could not be added." },
    country: "Country of origin",
    pricePlaceholder: "0 USD",
    initialStock: "Initial stock",
    informationPlaceholder: "Dimensions, color, materials, packaging...",
    noArticles: "No articles found.",
    openDetails: "Open product details",
    pricing: "Pricing",
    noImages: "No images for this product",
    noInformation: "No additional information.",
    cancel: "Cancel",
    sort: "Sort",
    errors: {
      invalid: "Complete all required fields with valid prices.",
      invalidImages: "Add valid PNG images, with a maximum of 8 and 1 MB per image.",
      invalidCategory: "Choose a category configured in Settings.",
      duplicate: "An article with this SKU already exists.",
      unauthorized: "Your session has expired. Sign in again.",
      unknown: "The article could not be created. Please try again.",
    },
  },
  fr: {
    title: "Articles",
    description: "Produits, fournisseurs, prix et lieux d’approvisionnement.",
    newArticle: "Nouvel article",
    createArticle: "Créer l’article",
    creating: "Création...",
    createDescription: "Ajoutez le produit, son fournisseur, ses prix et sa provenance.",
    search: "Rechercher des articles...",
    article: "Produit",
    sku: "SKU",
    category: "Catégorie",
    supplier: "Fournisseur",
    purchasePrice: "Prix d’achat",
    salePrice: "Prix de vente",
    transportCost: "Coût de transport",
    paymentCommission: "Commission de paiement",
    chinaTransportCost: "Transport achat",
    agencyTransportCost: "Transport agence",
    gainMultiplier: "Indice de gain (×1,5–×10)",
    totalCost: "Coût total",
    suggestedSalePrice: "Prix de vente proposé",
    markup: "Majoration",
    location: "Localisation",
    added: "Créé le",
    rating: "Note",
    reviews: "avis",
    stock: "Stock",
    units: "unités",
    buy: "Acheter",
    buying: "Achat...",
    outOfStock: "Épuisé",
    information: "Informations",
    images: "Images PNG",
    imagesHint: "Facultatif — jusqu’à 8 images PNG.",
    imagePicker: {
      choose: "Choisir des fichiers PNG",
      drop: "Déposez vos images PNG ici",
      paste: "ou collez une image avec Ctrl/Cmd + V",
      format: "PNG uniquement · 1 Mo maximum par image · 8 images maximum",
      invalidType: "Seules les images PNG sont acceptées.",
      tooLarge: "Chaque image doit peser au maximum 1 Mo.",
      tooMany: "Vous pouvez ajouter jusqu’à 8 images.",
      remove: "Supprimer",
    },
    namePlaceholder: "Ex. Montre premium en acier",
    skuPlaceholder: "Facultatif — généré automatiquement",
    categoryPlaceholder: "Ex. Accessoires",
    selectCategory: "Sélectionner une catégorie",
    createCategoryFromList: "Créer une catégorie",
    createCategory: "Créer",
    creatingCategory: "Création...",
    newCategoryName: "Nom de la nouvelle catégorie",
    categoryErrors: {
      invalid: "Saisissez un nom de catégorie valide.",
      duplicate: "Cette catégorie existe déjà.",
      unauthorized: "Votre session a expiré. Reconnectez-vous.",
      unknown: "La catégorie n’a pas pu être créée. Réessayez.",
    },
    supplierPlaceholder: "Ex. Atlas Trading",
    city: "Ville d’origine",
    selectCity: "Sélectionner une ville",
    newCityPlaceholder: "Ajouter une ville",
    addCity: "Ajouter",
    cityErrors: { invalid: "Saisissez une ville valide.", duplicate: "Cette ville existe déjà.", unauthorized: "Votre session a expiré.", unknown: "La ville n’a pas pu être ajoutée." },
    country: "Pays d’origine",
    pricePlaceholder: "0 USD",
    initialStock: "Stock initial",
    informationPlaceholder: "Dimensions, couleur, matériaux, emballage...",
    noArticles: "Aucun article trouvé.",
    openDetails: "Ouvrir les détails du produit",
    pricing: "Tarification",
    noImages: "Aucune image pour ce produit",
    noInformation: "Aucune information supplémentaire.",
    cancel: "Annuler",
    sort: "Trier",
    errors: {
      invalid: "Complétez les champs obligatoires avec des prix valides.",
      invalidImages: "Ajoutez des images PNG valides, avec un maximum de 8 et 1 Mo par image.",
      invalidCategory: "Choisissez une catégorie configurée dans Paramètres.",
      duplicate: "Un article avec ce SKU existe déjà.",
      unauthorized: "Votre session a expiré. Reconnectez-vous.",
      unknown: "L’article n’a pas pu être créé. Réessayez.",
    },
  },
} as const;
