import type { DashboardLanguage } from "../language";

export const settingsCopy = {
  en: {
    title: "Settings",
    description: "Configure how amounts are displayed across your workspace.",
    pricing: "Rates and prices",
    pricingDescription:
      "Prices are always stored in US dollars. Choose the currency used for display.",
    exchangeRate: "USD to CDF exchange rate",
    exchangeRateHelp: "Number of Congolese francs equivalent to 1 US dollar.",
    displayCurrency: "Default display currency",
    displayCurrencyHelp: "This selection is applied to every price in the application.",
    usd: "US dollar (USD)",
    cdf: "Congolese franc (CDF)",
    baseCurrency: "Base currency",
    baseCurrencyNotice: "All entered and stored prices remain in USD.",
    preview: "Preview",
    previewFormula: "100 USD × exchange rate, rounded up to the next multiple of CDF 500",
    save: "Save settings",
    saving: "Saving...",
    saved: "Pricing settings saved.",
    carriers: "Carriers",
    carriersDescription: "Build the carrier list used when launching a new order.",
    carrierName: "Carrier name",
    carrierInformation: "Information and notes",
    carrierInformationPlaceholder: "Contacts, phone numbers, routes, conditions or any useful text...",
    addCarrier: "Add carrier",
    addingCarrier: "Adding...",
    carrierList: "Configured carriers",
    noCarriers: "No carrier has been configured yet.",
    deleteCarrier: "Delete carrier",
    deleteCarrierConfirmation: "This carrier will be removed from future orders. Existing orders will keep its name.",
    delete: "Delete",
    cancel: "Cancel",
    carrierErrors: {
      invalid: "Enter a carrier name and valid information.",
      duplicate: "A carrier with this name already exists.",
      unauthorized: "Your session has expired. Sign in again.",
      unknown: "The carrier could not be saved. Please try again.",
    },
    errors: {
      invalid: "Enter a valid positive exchange rate and choose USD or CDF.",
      unauthorized: "Your session has expired. Sign in again.",
      unknown: "The settings could not be saved. Please try again.",
    },
  },
  fr: {
    title: "Paramètres",
    description: "Configurez l’affichage des montants dans votre espace de travail.",
    pricing: "Taux et prix",
    pricingDescription:
      "Les prix sont toujours enregistrés en dollars américains. Choisissez la devise d’affichage.",
    exchangeRate: "Taux USD vers CDF",
    exchangeRateHelp: "Nombre de francs congolais correspondant à 1 dollar américain.",
    displayCurrency: "Devise affichée par défaut",
    displayCurrencyHelp: "Ce choix sera appliqué à tous les prix de l’application.",
    usd: "Dollar américain (USD)",
    cdf: "Franc congolais (CDF)",
    baseCurrency: "Devise de base",
    baseCurrencyNotice: "Tous les prix saisis et enregistrés restent en USD.",
    preview: "Aperçu",
    previewFormula: "100 USD × le taux, arrondi par excès au multiple de 500 CDF",
    save: "Enregistrer les paramètres",
    saving: "Enregistrement...",
    saved: "Les paramètres de prix ont été enregistrés.",
    carriers: "Transporteurs",
    carriersDescription: "Concevez la liste des transporteurs utilisée lors du lancement d’une commande.",
    carrierName: "Nom du transporteur",
    carrierInformation: "Informations et notes",
    carrierInformationPlaceholder: "Contacts, numéros de téléphone, itinéraires, conditions ou tout texte utile...",
    addCarrier: "Ajouter le transporteur",
    addingCarrier: "Ajout...",
    carrierList: "Transporteurs configurés",
    noCarriers: "Aucun transporteur n’a encore été configuré.",
    deleteCarrier: "Supprimer le transporteur",
    deleteCarrierConfirmation: "Ce transporteur sera retiré des prochaines commandes. Les commandes existantes conserveront son nom.",
    delete: "Supprimer",
    cancel: "Annuler",
    carrierErrors: {
      invalid: "Saisissez un nom de transporteur et des informations valides.",
      duplicate: "Un transporteur portant ce nom existe déjà.",
      unauthorized: "Votre session a expiré. Reconnectez-vous.",
      unknown: "Le transporteur n’a pas pu être enregistré. Réessayez.",
    },
    errors: {
      invalid: "Saisissez un taux positif valide et choisissez USD ou CDF.",
      unauthorized: "Votre session a expiré. Reconnectez-vous.",
      unknown: "Les paramètres n’ont pas pu être enregistrés. Réessayez.",
    },
  },
} as const satisfies Record<DashboardLanguage, object>;
