export const stockCopy = {
  en: {
    title: "Stock management",
    description: "Track quantities, record entries and exits, and keep a complete audit trail.",
    totalUnits: "Total units",
    products: "Products",
    lowStock: "Low stock",
    outOfStock: "Out of stock",
    search: "Search by product, SKU or category...",
    product: "Product",
    category: "Category",
    currentStock: "Current stock",
    status: "Status",
    action: "Action",
    adjust: "Adjust stock",
    available: "Available",
    low: "Low",
    empty: "Out of stock",
    units: "units",
    openDetails: "View history and product information",
    noProducts: "No products found.",
    movementHistory: "Movement history",
    movementHistoryDescription: "All manual changes and recorded sales.",
    date: "Date",
    movement: "Movement",
    quantity: "Quantity",
    beforeAfter: "Before → after",
    reason: "Reason",
    createdBy: "Created by",
    noMovements: "No stock movement has been recorded yet.",
    noProductMovements: "No stock movement has been recorded for this product.",
    showAllMovements: "Show all movements",
    information: "Information",
    noInformation: "No additional information.",
    entry: "Entry",
    exit: "Exit",
    sale: "Sale",
    adjustTitle: "Adjust product stock",
    adjustDescription: "Record an entry or exit. The current quantity will be updated immediately.",
    operation: "Operation",
    selectOperation: "Select an operation",
    quantityLabel: "Quantity",
    reasonLabel: "Reason",
    reasonPlaceholder: "e.g. Supplier delivery, damaged goods...",
    current: "Current",
    newStock: "New stock",
    cancel: "Cancel",
    save: "Save movement",
    saving: "Saving...",
    errors: {
      invalid: "Enter a valid quantity and reason.",
      notFound: "This product no longer exists.",
      insufficient: "The requested exit exceeds the available stock.",
      unauthorized: "Your session has expired. Sign in again.",
      unknown: "The movement could not be saved. Please try again.",
    },
  },
  fr: {
    title: "Gestion de stock",
    description: "Suivez les quantités, enregistrez les entrées et sorties et conservez un historique complet.",
    totalUnits: "Unités en stock",
    products: "Articles",
    lowStock: "Stock faible",
    outOfStock: "Rupture de stock",
    search: "Rechercher par article, SKU ou catégorie...",
    product: "Article",
    category: "Catégorie",
    currentStock: "Stock actuel",
    status: "État",
    action: "Action",
    adjust: "Ajuster le stock",
    available: "Disponible",
    low: "Faible",
    empty: "En rupture",
    units: "unités",
    openDetails: "Voir l’historique et les informations de l’article",
    noProducts: "Aucun article trouvé.",
    movementHistory: "Historique des mouvements",
    movementHistoryDescription: "Toutes les modifications manuelles et ventes enregistrées.",
    date: "Date",
    movement: "Mouvement",
    quantity: "Quantité",
    beforeAfter: "Avant → après",
    reason: "Motif",
    createdBy: "Créé par",
    noMovements: "Aucun mouvement de stock n’a encore été enregistré.",
    noProductMovements: "Aucun mouvement de stock n’a été enregistré pour cet article.",
    showAllMovements: "Afficher tous les mouvements",
    information: "Informations",
    noInformation: "Aucune information supplémentaire.",
    entry: "Entrée",
    exit: "Sortie",
    sale: "Vente",
    adjustTitle: "Ajuster le stock de l’article",
    adjustDescription: "Enregistrez une entrée ou une sortie. La quantité sera mise à jour immédiatement.",
    operation: "Opération",
    selectOperation: "Choisir une opération",
    quantityLabel: "Quantité",
    reasonLabel: "Motif",
    reasonPlaceholder: "Ex. Livraison fournisseur, article endommagé…",
    current: "Actuel",
    newStock: "Nouveau stock",
    cancel: "Annuler",
    save: "Enregistrer le mouvement",
    saving: "Enregistrement...",
    errors: {
      invalid: "Saisissez une quantité et un motif valides.",
      notFound: "Cet article n’existe plus.",
      insufficient: "La sortie demandée dépasse le stock disponible.",
      unauthorized: "Votre session a expiré. Reconnectez-vous.",
      unknown: "Le mouvement n’a pas pu être enregistré. Réessayez.",
    },
  },
} as const;
