export const ordersCopy = {
  en: {
    title: "Active orders",
    description: "Create, launch and track client orders from origin to destination.",
    newOrder: "New order",
    createOrder: "Create order",
    launchOrder: "Launch order",
    creating: "Creating...",
    createDescription: "Select one or more articles, then add the shipment route.",
    article: "Article",
    articles: "Ordered articles",
    addArticle: "Add article",
    removeArticle: "Remove article",
    itemQuantity: "Quantity",
    selectArticle: "Select an article",
    client: "Client",
    noClient: "No client assigned",
    allClients: "All clients",
    allTransportModes: "All transport modes",
    dateFrom: "Created from",
    dateTo: "Created until",
    ordersTable: "All orders",
    printReceipt: "Print order",
    printA4: "Purchase order · A4 (client + stock)",
    printThermal: "Purchase order · 80 mm",
    printFiltered: "Print filtered orders",
    orderReceipt: "Order receipt",
    printedOn: "Printed on",
    createArticleFirst: "Create an article first",
    createArticleFirstHint: "An article is required before launching an order.",
    all: "All",
    inTransit: "In transit",
    delivered: "Delivered",
    delayed: "Delayed",
    onHold: "On hold",
    search: "Search orders...",
    noOrders: "No orders found.",
    originCountry: "Origin country",
    originCity: "Origin city / facility (optional)",
    destinationCountry: "Destination country",
    destinationCity: "Destination city / facility (optional)",
    selectCity: "Select a city",
    cargo: "Cargo",
    cargoPlaceholder: "e.g. Consumer electronics",
    carrier: "Carrier",
    carrierPlaceholder: "e.g. Maersk",
    selectCarrier: "Select a carrier",
    createCarrier: "Create a carrier",
    carrierName: "Carrier name",
    carrierInformation: "Information (optional)",
    carrierInformationPlaceholder: "e.g. Contact details or service notes",
    noConfiguredCarriers: "No configured carrier",
    configureCarriersFirst: "Add a carrier in Settings before launching an order.",
    transportMode: "Transport mode",
    air: "Air freight",
    sea: "Sea freight",
    road: "Road freight",
    rail: "Rail freight",
    weight: "Total weight (kg) — optional",
    quantity: "Quantity ordered",
    transportCost: "Transport cost",
    additionalCharges: "Additional charges",
    launchImmediately: "Launch this order now",
    launchImmediatelyHint: "When enabled, the quantity is added to stock and the order starts in transit.",
    draft: "Not launched",
    launchThisOrder: "Launch order",
    launching: "Launching...",
    cbm: "Volume (CBM) — optional",
    eta: "Estimated arrival",
    etaSuggestion: "Suggested: {days} days after launch. You can change this date.",
    cancel: "Cancel",
    overview: "Overview",
    route: "Route",
    cargoTab: "Cargo",
    activity: "Activity",
    orderDetails: "Order details",
    progress: "complete",
    created: "Created",
    estimatedArrival: "Estimated arrival",
    routeSummary: "Route summary",
    cargoDetails: "Cargo details",
    purchaseInformation: "Purchase information",
    purchaseUnitPrice: "Purchase price / unit",
    totalPurchase: "Total purchase",
    createdBy: "Created by",
    reference: "Reference",
    status: "Status",
    noSelection: "Select an order to view its details.",
    errors: {
      invalid: "Complete the required fields with valid information.",
      articleRequired: "Select valid, distinct articles from your workspace.",
      unauthorized: "Your session has expired. Sign in again.",
      unknown: "The order could not be created. Please try again.",
    },
  },
  fr: {
    title: "Commandes lancées",
    description: "Créez, lancez et suivez les commandes clients, de l’origine à la destination.",
    newOrder: "Nouvelle commande",
    createOrder: "Créer la commande",
    launchOrder: "Lancer la commande",
    creating: "Création...",
    createDescription: "Sélectionnez un ou plusieurs articles, puis ajoutez l’itinéraire.",
    article: "Article",
    articles: "Articles commandés",
    addArticle: "Ajouter un article",
    removeArticle: "Retirer l’article",
    itemQuantity: "Quantité",
    selectArticle: "Sélectionner un article",
    client: "Client",
    noClient: "Sans client",
    allClients: "Tous les clients",
    allTransportModes: "Tous les transports",
    dateFrom: "Créée à partir du",
    dateTo: "Créée jusqu’au",
    ordersTable: "Toutes les commandes",
    printReceipt: "Imprimer le bon",
    printA4: "Bon de commande · A4 (client + stock)",
    printThermal: "Bon de commande · 80 mm",
    printFiltered: "Imprimer les commandes filtrées",
    orderReceipt: "Reçu de commande",
    printedOn: "Imprimé le",
    createArticleFirst: "Créer d’abord un article",
    createArticleFirstHint: "Un article est obligatoire avant de lancer une commande.",
    all: "Toutes",
    inTransit: "En transit",
    delivered: "Livrées",
    delayed: "Retardées",
    onHold: "En attente",
    search: "Rechercher une commande...",
    noOrders: "Aucune commande trouvée.",
    originCountry: "Pays d’origine",
    originCity: "Ville / site d’origine (facultatif)",
    destinationCountry: "Pays de destination",
    destinationCity: "Ville / site de destination (facultatif)",
    selectCity: "Sélectionner une ville",
    cargo: "Cargaison",
    cargoPlaceholder: "Ex. Équipements électroniques",
    carrier: "Transporteur",
    carrierPlaceholder: "Ex. Maersk",
    selectCarrier: "Sélectionner un transporteur",
    createCarrier: "Créer un transporteur",
    carrierName: "Nom du transporteur",
    carrierInformation: "Informations (facultatif)",
    carrierInformationPlaceholder: "Ex. Contact ou notes de service",
    noConfiguredCarriers: "Aucun transporteur configuré",
    configureCarriersFirst: "Ajoutez un transporteur dans Paramètres avant de lancer une commande.",
    transportMode: "Mode de transport",
    air: "Fret aérien",
    sea: "Fret maritime",
    road: "Transport routier",
    rail: "Transport ferroviaire",
    weight: "Poids total (kg) — facultatif",
    quantity: "Quantité commandée",
    transportCost: "Coût du transport",
    additionalCharges: "Charges additionnelles",
    launchImmediately: "Lancer cette commande maintenant",
    launchImmediatelyHint: "Une fois lancée, la quantité est ajoutée au stock et la commande passe en transit.",
    draft: "Non lancée",
    launchThisOrder: "Lancer la commande",
    launching: "Lancement...",
    cbm: "Volume (CBM) — facultatif",
    eta: "Arrivée estimée",
    etaSuggestion: "Suggestion : {days} jours après le lancement. Vous pouvez modifier cette date.",
    cancel: "Annuler",
    overview: "Vue d’ensemble",
    route: "Itinéraire",
    cargoTab: "Cargaison",
    activity: "Activité",
    orderDetails: "Détails de la commande",
    progress: "terminé",
    created: "Créée",
    estimatedArrival: "Arrivée estimée",
    routeSummary: "Résumé de l’itinéraire",
    cargoDetails: "Détails de la cargaison",
    purchaseInformation: "Informations d’achat",
    purchaseUnitPrice: "Prix d’achat / unité",
    totalPurchase: "Total de l’achat",
    createdBy: "Créée par",
    reference: "Référence",
    status: "Statut",
    noSelection: "Sélectionnez une commande pour afficher ses détails.",
    errors: {
      invalid: "Complétez les champs obligatoires avec des informations valides.",
      articleRequired: "Sélectionnez des articles valides et distincts appartenant à votre espace.",
      unauthorized: "Votre session a expiré. Reconnectez-vous.",
      unknown: "La commande n’a pas pu être créée. Réessayez.",
    },
  },
} as const;
