export const ordersCopy = {
  en: {
    title: "Active orders",
    description: "Track every launched order from origin to destination.",
    newOrder: "New order",
    createOrder: "Launch order",
    creating: "Creating...",
    createDescription: "Select an existing article, then add the shipment route.",
    article: "Article",
    selectArticle: "Select an article",
    createArticleFirst: "Create an article first",
    createArticleFirstHint: "An article is required before launching an order.",
    all: "All",
    inTransit: "In transit",
    delivered: "Delivered",
    delayed: "Delayed",
    onHold: "On hold",
    search: "Search orders...",
    noOrders: "No orders found.",
    originCountry: "Origin country",
    originCity: "Origin city / facility (optional)",
    destinationCountry: "Destination country",
    destinationCity: "Destination city / facility (optional)",
    selectCity: "Select a city",
    cargo: "Cargo",
    cargoPlaceholder: "e.g. Consumer electronics",
    carrier: "Carrier",
    carrierPlaceholder: "e.g. Maersk",
    selectCarrier: "Select a carrier",
    createCarrier: "Create a carrier",
    carrierName: "Carrier name",
    carrierInformation: "Information (optional)",
    carrierInformationPlaceholder: "e.g. Contact details or service notes",
    noConfiguredCarriers: "No configured carrier",
    configureCarriersFirst: "Add a carrier in Settings before launching an order.",
    transportMode: "Transport mode",
    air: "Air freight",
    sea: "Sea freight",
    road: "Road freight",
    rail: "Rail freight",
    weight: "Total weight (kg) — optional",
    quantity: "Quantity ordered",
    cbm: "Volume (CBM) — optional",
    eta: "Estimated arrival",
    etaAutomatic: "Automatically calculated: 90 days after launch",
    cancel: "Cancel",
    overview: "Overview",
    route: "Route",
    cargoTab: "Cargo",
    activity: "Activity",
    orderDetails: "Order details",
    progress: "complete",
    created: "Created",
    estimatedArrival: "Estimated arrival",
    routeSummary: "Route summary",
    cargoDetails: "Cargo details",
    purchaseInformation: "Purchase information",
    purchaseUnitPrice: "Purchase price / unit",
    totalPurchase: "Total purchase",
    createdBy: "Created by",
    reference: "Reference",
    status: "Status",
    noSelection: "Select an order to view its details.",
    errors: {
      invalid: "Complete the required fields with valid information.",
      articleRequired: "Select an article that belongs to your workspace.",
      unauthorized: "Your session has expired. Sign in again.",
      unknown: "The order could not be created. Please try again.",
    },
  },
  fr: {
    title: "Commandes lancées",
    description: "Suivez chaque commande lancée, de l’origine à la destination.",
    newOrder: "Nouvelle commande",
    createOrder: "Lancer la commande",
    creating: "Création...",
    createDescription: "Sélectionnez un article existant, puis ajoutez l’itinéraire.",
    article: "Article",
    selectArticle: "Sélectionner un article",
    createArticleFirst: "Créer d’abord un article",
    createArticleFirstHint: "Un article est obligatoire avant de lancer une commande.",
    all: "Toutes",
    inTransit: "En transit",
    delivered: "Livrées",
    delayed: "Retardées",
    onHold: "En attente",
    search: "Rechercher une commande...",
    noOrders: "Aucune commande trouvée.",
    originCountry: "Pays d’origine",
    originCity: "Ville / site d’origine (facultatif)",
    destinationCountry: "Pays de destination",
    destinationCity: "Ville / site de destination (facultatif)",
    selectCity: "Sélectionner une ville",
    cargo: "Cargaison",
    cargoPlaceholder: "Ex. Équipements électroniques",
    carrier: "Transporteur",
    carrierPlaceholder: "Ex. Maersk",
    selectCarrier: "Sélectionner un transporteur",
    createCarrier: "Créer un transporteur",
    carrierName: "Nom du transporteur",
    carrierInformation: "Informations (facultatif)",
    carrierInformationPlaceholder: "Ex. Contact ou notes de service",
    noConfiguredCarriers: "Aucun transporteur configuré",
    configureCarriersFirst: "Ajoutez un transporteur dans Paramètres avant de lancer une commande.",
    transportMode: "Mode de transport",
    air: "Fret aérien",
    sea: "Fret maritime",
    road: "Transport routier",
    rail: "Transport ferroviaire",
    weight: "Poids total (kg) — facultatif",
    quantity: "Quantité commandée",
    cbm: "Volume (CBM) — facultatif",
    eta: "Arrivée estimée",
    etaAutomatic: "Calcul automatique : 90 jours après le lancement",
    cancel: "Annuler",
    overview: "Vue d’ensemble",
    route: "Itinéraire",
    cargoTab: "Cargaison",
    activity: "Activité",
    orderDetails: "Détails de la commande",
    progress: "terminé",
    created: "Créée",
    estimatedArrival: "Arrivée estimée",
    routeSummary: "Résumé de l’itinéraire",
    cargoDetails: "Détails de la cargaison",
    purchaseInformation: "Informations d’achat",
    purchaseUnitPrice: "Prix d’achat / unité",
    totalPurchase: "Total de l’achat",
    createdBy: "Créée par",
    reference: "Référence",
    status: "Statut",
    noSelection: "Sélectionnez une commande pour afficher ses détails.",
    errors: {
      invalid: "Complétez les champs obligatoires avec des informations valides.",
      articleRequired: "Sélectionnez un article appartenant à votre espace.",
      unauthorized: "Votre session a expiré. Reconnectez-vous.",
      unknown: "La commande n’a pas pu être créée. Réessayez.",
    },
  },
} as const;
