import { PlutosLogo } from "@/components/plutos-logo";
import { formatPrice, type PriceSettings } from "@/lib/pricing";
import type { DashboardLanguage } from "../language";
import type { OrderRecord } from "./orders-workspace";

const printCopy = {
  en: {
    documentTitle: "Purchase order",
    documentSubtitle: "Purchase and shipment authorization",
    clientCopy: "Client copy",
    stockCopy: "Stock copy",
    page: "Page",
    continuation: "Continuation",
    orderInformation: "Order information",
    reference: "Reference",
    issueDate: "Issue date",
    status: "Status",
    requestedBy: "Requested by",
    parties: "Parties and logistics",
    customer: "Customer / beneficiary",
    carrier: "Carrier / agent",
    transport: "Transport mode",
    origin: "Origin",
    destination: "Destination",
    items: "Ordered items",
    description: "Description",
    quantity: "Qty",
    unitPrice: "Unit price",
    amount: "Amount",
    total: "Order total",
    costs: "Transport and charges",
    transportCost: "Transport cost",
    additionalCharges: "Additional charges",
    estimatedTotal: "Estimated total",
    shipment: "Shipment details",
    eta: "Estimated arrival",
    weight: "Total weight",
    volume: "Volume",
    progress: "Progress",
    terms: "Declaration",
    termsText: "This purchase order confirms the information shown above. The applicant and the agent agree to report any change affecting price, quantity, route or delivery time.",
    applicant: "Applicant",
    agent: "Agent / carrier",
    approval: "Approval",
    nameAndSignature: "Name, date and signature",
    printedOn: "Printed on",
    noCustomer: "Not assigned",
    notProvided: "Not provided",
    inTransit: "In transit",
    delivered: "Delivered",
    delayed: "Delayed",
    onHold: "On hold",
    draft: "Not launched",
    footer: "Generated by Plutos · Keep this document for your records",
  },
  fr: {
    documentTitle: "Bon de commande",
    documentSubtitle: "Autorisation d’achat et d’expédition",
    clientCopy: "Copie client",
    stockCopy: "Copie stock",
    page: "Page",
    continuation: "Suite",
    orderInformation: "Informations de la commande",
    reference: "Référence",
    issueDate: "Date d’émission",
    status: "Statut",
    requestedBy: "Demandé par",
    parties: "Parties et logistique",
    customer: "Client / bénéficiaire",
    carrier: "Transporteur / agent",
    transport: "Mode de transport",
    origin: "Origine",
    destination: "Destination",
    items: "Articles commandés",
    description: "Désignation",
    quantity: "Qté",
    unitPrice: "Prix unitaire",
    amount: "Montant",
    total: "Total de la commande",
    costs: "Transport et charges",
    transportCost: "Coût du transport",
    additionalCharges: "Charges additionnelles",
    estimatedTotal: "Total estimé",
    shipment: "Détails de l’expédition",
    eta: "Arrivée estimée",
    weight: "Poids total",
    volume: "Volume",
    progress: "Progression",
    terms: "Déclaration",
    termsText: "Ce bon de commande confirme les informations indiquées ci-dessus. Le demandeur et l’agent s’engagent à signaler toute modification du prix, de la quantité, de l’itinéraire ou du délai de livraison.",
    applicant: "Demandeur",
    agent: "Agent / transporteur",
    approval: "Approbation",
    nameAndSignature: "Nom, date et signature",
    printedOn: "Imprimé le",
    noCustomer: "Non attribué",
    notProvided: "Non renseigné",
    inTransit: "En transit",
    delivered: "Livrée",
    delayed: "Retardée",
    onHold: "En attente",
    draft: "Non lancée",
    footer: "Généré par Plutos · Conservez ce document dans vos archives",
  },
} as const;

export const PURCHASE_ORDER_ITEMS_PER_A5_PAGE = 5;

export function paginatePurchaseOrderItems(order: OrderRecord) {
  const pages: OrderRecord["items"][] = [];
  for (let index = 0; index < order.items.length; index += PURCHASE_ORDER_ITEMS_PER_A5_PAGE) {
    pages.push(order.items.slice(index, index + PURCHASE_ORDER_ITEMS_PER_A5_PAGE));
  }
  return pages.length > 0 ? pages : [order.items];
}

function formatUtcDate(value: string, language: DashboardLanguage, includeTime = false) {
  const date = new Date(value);
  const locale = language === "fr" ? "fr-FR" : "en-US";
  return new Intl.DateTimeFormat(locale, {
    day: "2-digit",
    month: "short",
    year: "numeric",
    ...(includeTime ? { hour: "2-digit", minute: "2-digit" } : {}),
    timeZone: "UTC",
  }).format(date);
}

function location(country: string, city: string) {
  return city ? `${city}, ${country}` : country;
}

export function PurchaseOrderPrint({
  order,
  language,
  priceSettings,
  printedAt,
  copyType,
  items = order.items,
  pageIndex = 0,
  pageCount = 1,
  thermal = false,
}: {
  order: OrderRecord;
  language: DashboardLanguage;
  priceSettings: PriceSettings;
  printedAt: string;
  copyType?: "client" | "stock";
  items?: OrderRecord["items"];
  pageIndex?: number;
  pageCount?: number;
  thermal?: boolean;
}) {
  const text = printCopy[language];
  const locale = language === "fr" ? "fr-CD" : "en-US";
  const total = order.items.reduce(
    (sum, item) => sum + item.purchaseUnitPrice * item.quantity,
    0,
  );
  const estimatedTotal = total + order.transportCost + order.additionalCharges;
  const status = order.status === "delivered"
    ? text.delivered
    : order.status === "delayed"
      ? text.delayed
      : order.status === "on_hold"
        ? text.onHold
        : order.status === "draft"
          ? text.draft
        : text.inTransit;

  return (
    <article className="purchase-order-document">
      <header className="purchase-order-header">
        <div className="purchase-order-brand">
          <PlutosLogo
            className="purchase-order-brand-logo"
            appearance={thermal ? "monochrome" : "light"}
            eager
          />
          <p className="purchase-order-muted">Transport · Logistique · Livraison</p>
        </div>
        <div className="purchase-order-heading">
          {(copyType || pageCount > 1) && (
            <span className="purchase-order-copy-label">
              {copyType === "client" ? text.clientCopy : copyType === "stock" ? text.stockCopy : null}
              {copyType && pageCount > 1 ? " · " : null}
              {pageCount > 1
                ? `${pageIndex === 0 ? text.page : text.continuation} ${pageIndex + 1}/${pageCount}`
                : null}
            </span>
          )}
          <h1>{text.documentTitle}</h1>
          <p>{text.documentSubtitle}</p>
          <strong>{order.reference}</strong>
        </div>
      </header>

      <section className="purchase-order-section purchase-order-preface">
        <h2>{text.orderInformation}</h2>
        <dl className="purchase-order-grid purchase-order-grid-4">
          <div><dt>{text.reference}</dt><dd className="purchase-order-mono">{order.reference}</dd></div>
          <div><dt>{text.issueDate}</dt><dd>{formatUtcDate(order.createdAt, language)}</dd></div>
          <div><dt>{text.status}</dt><dd>{status}</dd></div>
          <div><dt>{text.requestedBy}</dt><dd>{order.createdByEmail ?? text.notProvided}</dd></div>
        </dl>
      </section>

      <section className="purchase-order-section purchase-order-preface">
        <h2>{text.parties}</h2>
        <dl className="purchase-order-grid purchase-order-grid-5">
          <div><dt>{text.customer}</dt><dd>{order.clientName ?? text.noCustomer}</dd></div>
          <div><dt>{text.carrier}</dt><dd>{order.carrier}</dd></div>
          <div><dt>{text.transport}</dt><dd>{order.transportMode.toUpperCase()}</dd></div>
          <div><dt>{text.origin}</dt><dd>{location(order.originCountryName, order.originCity)}</dd></div>
          <div><dt>{text.destination}</dt><dd>{location(order.destinationCountryName, order.destinationCity)}</dd></div>
        </dl>
      </section>

      <section className="purchase-order-section purchase-order-items">
        <h2>{text.items}</h2>
        <table className="purchase-order-table">
          <thead>
            <tr>
              <th>{text.description}</th>
              <th>{text.quantity}</th>
              <th>{text.unitPrice}</th>
              <th>{text.amount}</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr className="purchase-order-item-row" key={item.id}>
                <td>
                  <div className="purchase-order-item-line">
                    <strong>{item.description}</strong>
                    <span aria-hidden="true">·</span>
                    <small>{item.sku}</small>
                  </div>
                </td>
                <td className="purchase-order-item-number">{item.quantity.toLocaleString(locale)}</td>
                <td className="purchase-order-item-number">{formatPrice(item.purchaseUnitPrice, priceSettings, locale)}</td>
                <td className="purchase-order-item-number">{formatPrice(item.purchaseUnitPrice * item.quantity, priceSettings, locale)}</td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr>
              <th colSpan={3}>{text.total}</th>
              <td className="purchase-order-item-number">{formatPrice(total, priceSettings, locale)}</td>
            </tr>
          </tfoot>
        </table>
      </section>

      <div className="purchase-order-lower-grid">
        <section className="purchase-order-section">
          <h2>{text.costs}</h2>
          <dl className="purchase-order-grid purchase-order-grid-4">
            <div><dt>{text.total}</dt><dd>{formatPrice(total, priceSettings, locale)}</dd></div>
            <div><dt>{text.transportCost}</dt><dd>{formatPrice(order.transportCost, priceSettings, locale)}</dd></div>
            <div><dt>{text.additionalCharges}</dt><dd>{formatPrice(order.additionalCharges, priceSettings, locale)}</dd></div>
            <div><dt>{text.estimatedTotal}</dt><dd>{formatPrice(estimatedTotal, priceSettings, locale)}</dd></div>
          </dl>
        </section>

        <section className="purchase-order-section">
          <h2>{text.shipment}</h2>
          <dl className="purchase-order-grid purchase-order-grid-4">
            <div><dt>{text.eta}</dt><dd>{formatUtcDate(order.eta, language)}</dd></div>
            <div><dt>{text.weight}</dt><dd>{order.totalWeightKg === null ? text.notProvided : `${order.totalWeightKg.toLocaleString(locale)} kg`}</dd></div>
            <div><dt>{text.volume}</dt><dd>{order.cbm === null ? text.notProvided : `${order.cbm.toLocaleString(locale)} CBM`}</dd></div>
            <div><dt>{text.progress}</dt><dd>{order.progress}%</dd></div>
          </dl>
        </section>
      </div>

      <section className="purchase-order-section purchase-order-declaration">
        <h2>{text.terms}</h2>
        <div className="purchase-order-declaration-body">
          <p>{text.termsText}</p>
        </div>
      </section>

      <section className="purchase-order-signatures">
        {[text.applicant, text.agent, text.approval].map((label) => (
          <div key={label}>
            <strong>{label}</strong>
            <span>{text.nameAndSignature}</span>
          </div>
        ))}
      </section>

      <footer className="purchase-order-footer">
        <span>{text.footer}</span>
        <span>{text.printedOn}: {formatUtcDate(printedAt, language, true)} UTC</span>
      </footer>
    </article>
  );
}
