export const dashboardLanguages = ["en", "fr"] as const;

export type DashboardLanguage = (typeof dashboardLanguages)[number];

export function isDashboardLanguage(value: string): value is DashboardLanguage {
  return dashboardLanguages.includes(value as DashboardLanguage);
}

export const dashboardCopy = {
  en: {
    workspace: "Workspace",
    mainNavigation: "Main navigation",
    dashboard: "Dashboard",
    clients: "Clients",
    activeOrders: "Active orders",
    articles: "Articles",
    projectManagement: "Project management",
    todos: "To-do's",
    invoices: "Invoices",
    contracts: "Contracts",
    payments: "Payments",
    calendar: "Calendar / Meetings",
    notes: "Notes",
    settings: "Settings",
    projects: "Projects",
    designEngineering: "Design Engineering",
    salesMarketing: "Sales & Marketing",
    travel: "Travel",
    securityPrinting: "Security Printing",
    more: "More",
    helpCenter: "Help center",
    signedIn: "Signed in",
    signOut: "Sign out",
    language: "Language",
    english: "English",
    french: "French",
    collapseSidebar: "Collapse sidebar",
    openNavigation: "Open navigation",
    search: "Search",
    notifications: "Notifications",
    toggleTheme: "Toggle theme",
    invite: "Invite",
    workspaceOverview: "Workspace overview",
    download: "Download",
    overview: "Overview",
    analytics: "Analytics",
    reports: "Reports",
    totalRevenue: "Total revenue",
    subscriptions: "Subscriptions",
    sales: "Sales",
    activeNow: "Active now",
    lastMonth20: "+20.1% from last month",
    lastMonth180: "+180.1% from last month",
    lastMonth19: "+19% from last month",
    sinceLastMonth: "+201 since last month",
    leadsToClients: "Leads-to-clients",
    deployProject: "Deploy your next project in one click.",
    viewAll: "View all",
    lead: "Lead",
    qualified: "Qualified",
    proposal: "Proposal",
    negotiation: "Negotiation",
    monthlyRevenue: "Monthly revenue performance",
    todoLists: "To-do lists",
    manageWork: "Manage today's work here.",
    prepareProposal: "Prepare client proposal",
    reviewContracts: "Review new contracts",
    sendInvoices: "Send weekly invoices",
    dueToday: "Due today",
    dueTomorrow: "Due tomorrow",
    dueFriday: "Due Friday",
    recentProjects: "Recent projects",
    trackWork: "Track your latest client work.",
    view: "View",
    filterProjects: "Filter projects...",
    status: "Status",
    priority: "Priority",
    project: "Project",
    client: "Client",
    budget: "Budget",
    inProgress: "In progress",
    review: "Review",
    completed: "Completed",
    high: "High",
    medium: "Medium",
    low: "Low",
    sectionReady: "This section is ready for your live data.",
    clientRecordsDescription: "Recent client records with their phone and WhatsApp availability.",
    export: "Export",
    newClient: "New client",
    createClient: "Create client",
    creatingClient: "Creating...",
    createClientDescription: "Add the client's contact details and WhatsApp availability.",
    fullName: "Full name",
    fullNamePlaceholder: "e.g. Sarah Parker",
    phonePlaceholder: "e.g. +243 000 000 000",
    hasWhatsApp: "This number has WhatsApp",
    cancel: "Cancel",
    createClientErrors: {
      invalid: "Enter a valid name and phone number.",
      duplicate: "A client with this phone number already exists.",
      unauthorized: "Your session has expired. Sign in again.",
      unknown: "The client could not be created. Please try again.",
    },
    searchClients: "Search clients...",
    allWhatsAppStatuses: "All WhatsApp statuses",
    withWhatsApp: "With WhatsApp",
    withoutWhatsApp: "Without WhatsApp",
    yes: "Yes",
    no: "No",
    allDates: "All dates",
    lastSevenDays: "Last 7 days",
    lastThirtyDays: "Last 30 days",
    sort: "Sort",
    phone: "Phone number",
    whatsapp: "WhatsApp",
    writeOnWhatsApp: "Write on WhatsApp",
    joined: "Added",
    selectedRows: "row(s) selected",
    rowsPerPage: "Rows per page",
    page: "Page",
    of: "of",
    noClients: "No clients found.",
    previousPage: "Previous page",
    nextPage: "Next page",
    firstPage: "First page",
    lastPage: "Last page",
  },
  fr: {
    workspace: "Espace de travail",
    mainNavigation: "Navigation principale",
    dashboard: "Tableau de bord",
    clients: "Clients",
    activeOrders: "Commandes lancées",
    articles: "Articles",
    projectManagement: "Gestion de projets",
    todos: "Tâches",
    invoices: "Factures",
    contracts: "Contrats",
    payments: "Paiements",
    calendar: "Calendrier / Réunions",
    notes: "Notes",
    settings: "Paramètres",
    projects: "Projets",
    designEngineering: "Design et ingénierie",
    salesMarketing: "Ventes et marketing",
    travel: "Voyages",
    securityPrinting: "Security Printing",
    more: "Plus",
    helpCenter: "Centre d'aide",
    signedIn: "Connecté",
    signOut: "Se déconnecter",
    language: "Langue",
    english: "Anglais",
    french: "Français",
    collapseSidebar: "Réduire la navigation",
    openNavigation: "Ouvrir la navigation",
    search: "Rechercher",
    notifications: "Notifications",
    toggleTheme: "Changer le thème",
    invite: "Inviter",
    workspaceOverview: "Vue d'ensemble de l'espace",
    download: "Télécharger",
    overview: "Vue d'ensemble",
    analytics: "Analyses",
    reports: "Rapports",
    totalRevenue: "Revenu total",
    subscriptions: "Abonnements",
    sales: "Ventes",
    activeNow: "Actifs maintenant",
    lastMonth20: "+20,1 % depuis le mois dernier",
    lastMonth180: "+180,1 % depuis le mois dernier",
    lastMonth19: "+19 % depuis le mois dernier",
    sinceLastMonth: "+201 depuis le mois dernier",
    leadsToClients: "Prospects convertis",
    deployProject: "Transformez votre prochain prospect en un clic.",
    viewAll: "Tout voir",
    lead: "Prospect",
    qualified: "Qualifié",
    proposal: "Proposition",
    negotiation: "Négociation",
    monthlyRevenue: "Performance mensuelle des revenus",
    todoLists: "Liste des tâches",
    manageWork: "Gérez le travail du jour ici.",
    prepareProposal: "Préparer la proposition client",
    reviewContracts: "Réviser les nouveaux contrats",
    sendInvoices: "Envoyer les factures de la semaine",
    dueToday: "Pour aujourd'hui",
    dueTomorrow: "Pour demain",
    dueFriday: "Pour vendredi",
    recentProjects: "Projets récents",
    trackWork: "Suivez vos derniers projets clients.",
    view: "Afficher",
    filterProjects: "Filtrer les projets...",
    status: "Statut",
    priority: "Priorité",
    project: "Projet",
    client: "Client",
    budget: "Budget",
    inProgress: "En cours",
    review: "En révision",
    completed: "Terminé",
    high: "Haute",
    medium: "Moyenne",
    low: "Basse",
    sectionReady: "Cette section est prête à recevoir vos données réelles.",
    clientRecordsDescription: "Clients récents avec leur numéro et leur disponibilité sur WhatsApp.",
    export: "Exporter",
    newClient: "Nouveau client",
    createClient: "Créer le client",
    creatingClient: "Création...",
    createClientDescription: "Ajoutez les coordonnées du client et sa disponibilité sur WhatsApp.",
    fullName: "Nom complet",
    fullNamePlaceholder: "Ex. Sarah Parker",
    phonePlaceholder: "Ex. +243 000 000 000",
    hasWhatsApp: "Ce numéro utilise WhatsApp",
    cancel: "Annuler",
    createClientErrors: {
      invalid: "Saisissez un nom et un numéro de téléphone valides.",
      duplicate: "Un client utilise déjà ce numéro de téléphone.",
      unauthorized: "Votre session a expiré. Reconnectez-vous.",
      unknown: "Le client n’a pas pu être créé. Réessayez.",
    },
    searchClients: "Rechercher des clients...",
    allWhatsAppStatuses: "Tous les statuts WhatsApp",
    withWhatsApp: "Avec WhatsApp",
    withoutWhatsApp: "Sans WhatsApp",
    yes: "Oui",
    no: "Non",
    allDates: "Toutes les dates",
    lastSevenDays: "7 derniers jours",
    lastThirtyDays: "30 derniers jours",
    sort: "Trier",
    phone: "Numéro de téléphone",
    whatsapp: "WhatsApp",
    writeOnWhatsApp: "Écrire sur WhatsApp",
    joined: "Ajouté",
    selectedRows: "ligne(s) sélectionnée(s)",
    rowsPerPage: "Lignes par page",
    page: "Page",
    of: "sur",
    noClients: "Aucun client trouvé.",
    previousPage: "Page précédente",
    nextPage: "Page suivante",
    firstPage: "Première page",
    lastPage: "Dernière page",
  },
} as const;

export type DashboardCopy = (typeof dashboardCopy)[DashboardLanguage];
