export const todosCopy = {
  en: {
    title: "To-do's",
    description: "Plan, prioritize and complete your work.",
    newTask: "New task",
    createTask: "Create task",
    creatingTask: "Creating...",
    createDescription: "Add a task, its priority and an optional due date.",
    taskTitle: "Task title",
    titlePlaceholder: "e.g. Confirm supplier prices",
    details: "Description",
    detailsPlaceholder: "Add useful context...",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    dueDate: "Due date",
    noDueDate: "No due date",
    all: "All",
    pending: "Pending",
    completed: "Completed",
    search: "Search tasks...",
    remaining: "remaining",
    done: "completed",
    total: "total",
    noTasks: "No tasks found.",
    noTasksDescription: "Create your first task to start organizing your work.",
    markComplete: "Mark as completed",
    markPending: "Mark as pending",
    cancel: "Cancel",
    errors: {
      invalid: "Enter a valid task title and priority.",
      unauthorized: "Your session has expired. Sign in again.",
      unknown: "The task could not be saved. Please try again.",
    },
  },
  fr: {
    title: "Tâches",
    description: "Planifiez, priorisez et terminez votre travail.",
    newTask: "Nouvelle tâche",
    createTask: "Créer la tâche",
    creatingTask: "Création...",
    createDescription: "Ajoutez une tâche, sa priorité et une échéance facultative.",
    taskTitle: "Titre de la tâche",
    titlePlaceholder: "Ex. Confirmer les prix du fournisseur",
    details: "Description",
    detailsPlaceholder: "Ajoutez le contexte utile...",
    priority: "Priorité",
    low: "Basse",
    medium: "Moyenne",
    high: "Haute",
    dueDate: "Échéance",
    noDueDate: "Sans échéance",
    all: "Toutes",
    pending: "À faire",
    completed: "Terminées",
    search: "Rechercher des tâches...",
    remaining: "restantes",
    done: "terminées",
    total: "au total",
    noTasks: "Aucune tâche trouvée.",
    noTasksDescription: "Créez votre première tâche pour organiser votre travail.",
    markComplete: "Marquer comme terminée",
    markPending: "Marquer comme à faire",
    cancel: "Annuler",
    errors: {
      invalid: "Saisissez un titre et une priorité valides.",
      unauthorized: "Votre session a expiré. Reconnectez-vous.",
      unknown: "La tâche n’a pas pu être enregistrée. Réessayez.",
    },
  },
} as const;
