export const todosCopy = {
  en: {
    title: "To-do's",
    description: "Plan, prioritize and complete your work.",
    newTask: "New task",
    createTask: "Create task",
    creatingTask: "Creating...",
    createDescription: "Add a task, choose its tag and optionally attach a photo.",
    editTask: "Edit task",
    editDescription: "Update the task details, tag, photo or status.",
    saveChanges: "Save changes",
    savingChanges: "Saving...",
    taskTitle: "Task title",
    titlePlaceholder: "e.g. Confirm supplier prices",
    details: "Description",
    detailsPlaceholder: "Add useful context...",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    tag: "Tag",
    selectTag: "Select a tag",
    filterByTag: "Filter by tag",
    allTags: "All tags",
    tags: {
      general: "General",
      client: "Client",
      supplier: "Supplier",
      finance: "Finance",
      project: "Project",
      administrative: "Administrative",
    },
    photo: "Photo",
    photoOptional: "Optional",
    photoPicker: {
      choose: "Choose a photo",
      replace: "Replace photo",
      drop: "Drop a photo here",
      format: "PNG, JPEG or WebP · 8 MB max · automatically optimized",
      invalidType: "Choose a PNG, JPEG or WebP image.",
      tooLarge: "The photo is too large to be saved.",
      processingFailed: "The photo could not be prepared. Try another file.",
      remove: "Remove photo",
    },
    dueDate: "Due date",
    noDueDate: "No due date",
    all: "All",
    pending: "Pending",
    completed: "Completed",
    search: "Search tasks...",
    remaining: "remaining",
    done: "completed",
    total: "total",
    noTasks: "No tasks found.",
    noTasksDescription: "Create your first task to start organizing your work.",
    markComplete: "Mark as completed",
    markPending: "Mark as pending",
    status: "Status",
    taskCompleted: "Task completed",
    taskPending: "Task pending",
    createdOn: "Created on",
    openTask: "Open task",
    readOnlyTask: "Only the task owner can edit it.",
    cancel: "Cancel",
    errors: {
      invalid: "Enter a valid task title and choose a tag.",
      invalidPhoto: "The photo is invalid or too large.",
      unauthorized: "Your session has expired. Sign in again.",
      forbidden: "You are not allowed to edit this task.",
      unknown: "The task could not be saved. Please try again.",
    },
  },
  fr: {
    title: "Tâches",
    description: "Planifiez, priorisez et terminez votre travail.",
    newTask: "Nouvelle tâche",
    createTask: "Créer la tâche",
    creatingTask: "Création...",
    createDescription: "Ajoutez une tâche, choisissez son tag et joignez éventuellement une photo.",
    editTask: "Modifier la tâche",
    editDescription: "Modifiez les détails, le tag, la photo ou le statut de la tâche.",
    saveChanges: "Enregistrer les modifications",
    savingChanges: "Enregistrement...",
    taskTitle: "Titre de la tâche",
    titlePlaceholder: "Ex. Confirmer les prix du fournisseur",
    details: "Description",
    detailsPlaceholder: "Ajoutez le contexte utile...",
    priority: "Priorité",
    low: "Basse",
    medium: "Moyenne",
    high: "Haute",
    tag: "Tag",
    selectTag: "Choisir un tag",
    filterByTag: "Filtrer par tag",
    allTags: "Tous les tags",
    tags: {
      general: "Général",
      client: "Client",
      supplier: "Fournisseur",
      finance: "Finance",
      project: "Projet",
      administrative: "Administratif",
    },
    photo: "Photo",
    photoOptional: "Facultative",
    photoPicker: {
      choose: "Choisir une photo",
      replace: "Remplacer la photo",
      drop: "Déposez une photo ici",
      format: "PNG, JPEG ou WebP · 8 Mo max · optimisation automatique",
      invalidType: "Choisissez une image PNG, JPEG ou WebP.",
      tooLarge: "La photo est trop volumineuse pour être enregistrée.",
      processingFailed: "La photo n’a pas pu être préparée. Essayez un autre fichier.",
      remove: "Supprimer la photo",
    },
    dueDate: "Échéance",
    noDueDate: "Sans échéance",
    all: "Toutes",
    pending: "À faire",
    completed: "Terminées",
    search: "Rechercher des tâches...",
    remaining: "restantes",
    done: "terminées",
    total: "au total",
    noTasks: "Aucune tâche trouvée.",
    noTasksDescription: "Créez votre première tâche pour organiser votre travail.",
    markComplete: "Marquer comme terminée",
    markPending: "Marquer comme à faire",
    status: "Statut",
    taskCompleted: "Tâche terminée",
    taskPending: "Tâche à faire",
    createdOn: "Créée le",
    openTask: "Ouvrir la tâche",
    readOnlyTask: "Seul le propriétaire de la tâche peut la modifier.",
    cancel: "Annuler",
    errors: {
      invalid: "Saisissez un titre valide et choisissez un tag.",
      invalidPhoto: "La photo est invalide ou trop volumineuse.",
      unauthorized: "Votre session a expiré. Reconnectez-vous.",
      forbidden: "Vous n’êtes pas autorisé à modifier cette tâche.",
      unknown: "La tâche n’a pas pu être enregistrée. Réessayez.",
    },
  },
} as const;
